# Generated by Django 2.2.12 on 2020-04-25 05:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200419_1151'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('files', django.db.models.manager.Manager()),
            ],
        ),
    ]
